# Generated by Django 5.0 on 2023-12-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ValidationApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='car_color',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='car_manufacture_date',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='car_manufacture_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='plate_number',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='plate_type',
        ),
    ]
