# Generated by Django 5.0 on 2023-12-19 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValidationApp', '0002_remove_participant_car_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ValidationApp.participant'),
        ),
    ]
