# Generated by Django 5.0 on 2023-12-19 20:59

import ValidationApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValidationApp', '0003_alter_vehicle_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=10, validators=[ValidationApp.models.validate_rwandan_plate_number]),
        ),
    ]
