# Generated by Django 4.2.8 on 2023-12-20 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ValidationApp', '0005_alter_vehicle_plate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='participant',
            field=models.ForeignKey(blank=True, help_text='If this is the first time creating a participant, leave it empty.', null=True, on_delete=django.db.models.deletion.CASCADE, to='ValidationApp.participant'),
        ),
    ]
